channels:
- defaults
- conda-forge
dependencies:
- awscli=1.11.63=py36_0
- botocore=1.5.26=py36_0
- colorama=0.3.7=py36_0
- jmespath=0.9.2=py36_0
- pyasn1=0.2.3=py36_0
- python-dotenv=0.6.1=py36_0
- pyyaml=3.12=py36_1
- rsa=3.4.2=py36_0
- s3transfer=0.1.10=py36_1
- yaml=0.1.6=0
- alabaster=0.7.10=py36_0
- appnope=0.1.0=py36_0
- babel=2.4.0=py36_0
- click=6.7=py36_0
- coverage=4.3.4=py36_0
- decorator=4.0.11=py36_0
- docutils=0.13.1=py36_0
- imagesize=0.7.1=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.0.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jinja2=2.9.6=py36_0
- jupyter_client=5.0.1=py36_0
- jupyter_core=4.3.0=py36_0
- markupsafe=0.23=py36_2
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- openssl=1.0.2k=1
- pandas=0.19.2=np112py36_1
- path.py=10.3.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.2.0=py36_0
- python=3.6.1=0
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_0
- readline=6.2=2
- requests=2.13.0=py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- six=1.10.0=py36_0
- snowballstemmer=1.2.1=py36_0
- sphinx=1.5.4=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14